# Use OpenJDK 21 for Minecraft 1.20+
FROM eclipse-temurin:21-jre-jammy

# Set working directory
WORKDIR /minecraft

# Install wget and other utilities
RUN apt-get update && \
    apt-get install -y wget curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Download Fabric server launcher
# Update these versions as needed, then rebuild with: docker-compose build --no-cache
ARG FABRIC_VERSION=0.15.11
ARG MINECRAFT_VERSION=1.20.4
RUN wget -O fabric-server-launcher.jar \
    https://meta.fabricmc.net/v2/versions/loader/${MINECRAFT_VERSION}/${FABRIC_VERSION}/1.0.0/server/jar

# Create necessary directories
RUN mkdir -p /minecraft/mods /minecraft/config /minecraft/world

# Expose Minecraft server port
EXPOSE 25565

# Set environment variables with defaults
ENV JAVA_OPTS="-Xmx2G -Xms1G"
ENV EULA="false"

# Accept EULA if EULA environment variable is set to true
RUN echo "# Minecraft EULA" > eula.txt && \
    echo "# Generated by Docker container" >> eula.txt && \
    echo "eula=false" >> eula.txt

# Create startup script
RUN echo '#!/bin/bash\n\
if [ "$EULA" = "true" ]; then\n\
    echo "eula=true" > eula.txt\n\
fi\n\
exec java $JAVA_OPTS -jar fabric-server-launcher.jar nogui' > /minecraft/start.sh && \
    chmod +x /minecraft/start.sh

# Run the server
CMD ["/minecraft/start.sh"]
